#!/usr/bin/env bash

# Check yarn install
if [[ -z "$(which yarn)" ]]
then
	echo -e "\n--> Can't find the yarn command."
	echo -e "--> Make sure yarn is installed correctly. "
	echo -e "--> $ brew install yarn"

	exit 1

else
	echo -e "\n--> Yarn installed: OK"
	echo -e "    $(which yarn)"

fi

echo -e "\n--> Downloading gulp-starter\n"
curl -L https://github.com/mrhenry/gulp-starter/archive/master.zip > gulp-starter-master.zip

echo -e "\n--> Extracting\n"
unzip gulp-starter-master.zip

echo -e "\n--> Copying files\n"
rm gulp-starter/README.md
cp -R  gulp-starter-master/template/* ./
cp -R  gulp-starter-master/template/.[^.]* ./

echo -e "\n--> Bootstrapping\n"
PROJECT_SLUG=${PWD##*/}
PUBLIC_PATH=public

if [ -f wp-config.php ]
then
  PROJECT_SLUG=${PROJECT_SLUG/wp_/''}

  PUBLIC_PATH=wp-content/themes/$PROJECT_SLUG/public
fi

mkdir -p $PUBLIC_PATH

sed -i "s:{{PUBLIC_PATH}}:${PUBLIC_PATH}:g" ./gulp/config.js
sed -i "s:{{PROJECT_SLUG}}:${PROJECT_SLUG}:g" ./package.json
sed -i "s:{{PROJECT_SLUG}}:${PROJECT_SLUG}:g" ./gulp/config.js

echo -e "\nCreated public folder\n"

echo -e "\n--> Installing dependencies through Yarn\n"
yarn install

echo -e "\n--> Removing installation files\n"
rm -Rf ./gulp-starter-master*

echo -e "\n--> That's all, folks!\n"
